base_url = "https://valkey.io"
title = "Valkey"

compile_sass = true

build_search_index = true

generate_feeds = true

[markdown]
highlight_code = true

# Needed to stop certain command topics from being destroyed by the slugifier
[slugify]
"paths" = "safe"

# This is included to override any differences slugs and documentation source filenames
[extra.slug_source_exceptions]
"valkey-conf" = "valkey.conf"

[extra]
command_description_path = "../build-command-docs/"
command_json_path = "../build-command-json/"
client_json_path = "../build-clients/"
doc_topic_path = "../build-topics/"

review_list = [
    "/topics/license/",
    "/topics/admin/",
    "/topics/distlock/",
    "/topics/eval-intro/",
    "/topics/faq/",
    "/topics/functions-intro/",
    "/topics/hashes/",
    "/topics/internals-eventlib/",
    "/topics/internals-vm/",
    "/topics/internals/",
    "/topics/latency/",
    "/topics/lua-api/",
    "/topics/rdd/",
    "/topics/history/"
]

publish_hold = [
    "/topics/license/",
    "/topics/internals-eventlib/",
    "/topics/internals-vm/",
    "/topics/internals/",
    "/topics/rdd/"
]

recommended_clients_paths = [
    "/python/github.com/AWS/valkey-GLIDE.json",
    "/python/github.com/valkey/valkey-py.json",
    "/nodejs/github.com/AWS/valkey-GLIDE.json",
    "/nodejs/github.com/valkey/iovalkey.json",
    "/java/github.com/AWS/valkey-GLIDE.json",
    "/java/github.com/valkey/valkey-java.json",
    "/go/github.com/valkey/valkey-go.json",
    "/php/github.com/phpredis/phpredis.json",
    "/php/github.com/nrk/predis.json",
]