base_url = "https://valkey.io"
title = "Valkey"

compile_sass = true

build_search_index = true

generate_feeds = true

[markdown]
highlight_code = true

# Needed to stop certain command topics from being destroyed by the slugifier
[slugify]
"paths" = "safe"

# This is included to override any differences slugs and documentation source filenames
[extra.slug_source_exceptions]
"valkey-conf" = "valkey.conf"

[extra]
command_description_path = "../build-command-docs/"
command_json_path = "../build-command-json/"
doc_topic_path = "../build-topics/"

review_list = [
    "/topics/license/",
    "/topics/admin/",
    "/topics/distlock/",
    "/topics/eval-intro/",
    "/topics/faq/",
    "/topics/functions-intro/",
    "/topics/hashes/",
    "/topics/internals-eventlib/",
    "/topics/internals-vm/",
    "/topics/internals/",
    "/topics/latency/",
    "/topics/lua-api/",
    "/topics/modules-blocking-ops/",
    "/topics/modules-intro/",
    "/topics/pipelining/",
    "/topics/programmability/",
    "/topics/protocol/",
    "/topics/pubsub/",
    "/topics/rdd/",
    "/topics/replication/",
    "/topics/security/",
    "/topics/sentinel-clients/",
    "/topics/sentinel/",
    "/topics/transactions/",
    "/topics/cluster-spec/",
    "/topics/history/"
]

publish_hold = [
    "/topics/protocol/",
    "/topics/license/",
    "/topics/internals-eventlib/",
    "/topics/internals-vm/",
    "/topics/internals/",
    "/topics/protocol/",
    "/topics/rdd/"
]

banner = "Valkey 8.0.0 has [higher performance](/blog/unlock-one-million-rps/) and [better memory efficiency](/blog/valkey-memory-efficiency-8-0/). Get [Valkey 8.0.0](/download/releases/v8-0-0/) today!"
