name: Deploy website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: >-
            ${{ github.event_name == 'pull_request' &&
                github.head_ref || 'main' }}
          repository: >-
            ${{ github.event_name == 'pull_request' &&
                github.event.pull_request.head.repo.full_name || 'valkey-io/valkey-io.github.io' }}
          path: website

      - name: Checkout valkey-doc
        uses: actions/checkout@v4
        with:
          repository: valkey-io/valkey-doc
          path: valkey-doc

      - name: Checkout valkey
        uses: actions/checkout@v4
        with:
          repository: valkey-io/valkey
          path: valkey

      - name: Checkout valkey-bloom
        uses: actions/checkout@v4
        with:
          repository: valkey-io/valkey-bloom
          path: valkey-bloom

      - name: Checkout valkey-search
        uses: actions/checkout@v4
        with:
          repository: valkey-io/valkey-search
          path: valkey-search

      - name: Checkout valkey-json
        uses: actions/checkout@v4
        with:
          repository: valkey-io/valkey-json
          path: valkey-json

      - name: Init commands, topics and clients
        run: |
          cd website
          ./build/init-topics-and-clients.sh ../valkey-doc/topics \
            ../valkey-doc/clients
          ./build/init-commands.sh ../valkey-doc/commands \
            ../valkey/src/commands ../valkey-bloom/src/commands \
            ../valkey-json/src/commands ../valkey-search/src/commands

      - name: Build only
        uses: shalzz/zola-deploy-action@v0.22.0
        env:
          BUILD_DIR: website
          BUILD_ONLY: true
          BUILD_THEMES: false

      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/public

  deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
